env:
  data_file:   data/eurusd_1s/EURUSD_ALL.parquet   # 12-month Parquet
  bar_seconds: 5
  train_start: "2024-05-01"
  train_end:   "2025-01-31"
  test_start:  "2025-02-01"
  test_end:    "2025-05-01"

  lambda_dd:   0.0002      # 10× smaller → easier early learning
  commission:  0.00000     # OFF for this run; re-enable later
  reset_on_day_change: true

ppo:
  total_timesteps:  1_000_000
  n_steps:          2048          # bigger batch → stabler gradients
  batch_size:       2048
  learning_rate:    1.0e-4
  gamma:            0.997
  gae_lambda:       0.95
  clip_range:       0.2
  ent_coef:         0.001         # encourage exploration

misc:
  seed:     42
  log_dir:  logs/exp_kz_round
  save_every_steps: 250_000       # checkpoints 