env:
  data_file: data/eurusd_1s/EURUSD_ALL.parquet
  bar_seconds: 1
  train_start: "2024-05-01"
  train_end:   "2025-01-31"
  test_start:  "2025-02-01"
  test_end:    "2025-05-01"
  lambda_dd:   0.001
  commission:  0.00007

ppo:
  total_timesteps: 5000000
  n_steps: 1024
  batch_size: 1024
  learning_rate: 1.0e-4
  n_epochs: 10
  gamma: 0.99
  gae_lambda: 0.95
  clip_range: 0.2
  clip_range_vf: null
  normalize_advantage: true
  ent_coef: 0.01
  vf_coef: 0.5
  max_grad_norm: 0.5
  use_sde: false
  sde_sample_freq: -1
  target_kl: null
  tensorboard_log: "logs/tensorboard"
  policy_kwargs:
    net_arch:
      pi: [64, 64]
      vf: [64, 64]
    activation_fn: "tanh" 