env:
  data_file: data/eurusd_ticks.csv
  bar_seconds: 1
  lambda_dd: 0.001
  commission: 0.00005

ppo:
  learning_rate: 3.0e-4
  n_steps: 256
  batch_size: 256
  n_epochs: 10
  gamma: 0.995
  gae_lambda: 0.95
  clip_range: 0.2
  clip_range_vf: null
  normalize_advantage: true
  ent_coef: 0.0
  vf_coef: 0.5
  max_grad_norm: 0.5
  use_sde: false
  sde_sample_freq: -1
  target_kl: null
  tensorboard_log: null
  policy_kwargs: null
  verbose: 0
  seed: 42
  device: auto
  _init_setup_model: true

misc:
  total_timesteps: 200000
  log_dir: ./logs 